Update Mensa.tex
fsphys-muenster/ersti-fibel pull request #98
Opened 2022-08-05 09:29 UTC by MoosWhmr

Ziemlich viel Text geändert und Angaben rausgenommen die entweder nicht mehr aktuell sind oder bei denen ich mir gerade nicht sicher bin. Ich muss das auch nochmal Korrekturlesen.

2022-08-05 11:42 UTC, willernicht commented
Meinst du nicht, du könntest mal den PR #95 mergen?! 
Oder mir wenigstens Rechte geben, dies zu tun?!

2022-09-09 08:39 UTC, MoosWhmr commented
Änderungen von Marius gelesen und für gut befunden. Ich kann als Ersteller des PR nur nicht approven.

2022-09-20 07:47 UTC, axti98 requested changes
Zeile 15: Wer dies umgehen möchte: Komma hinter möchte fehlt.
Zeile 17: "ein Bisschen", Entweder guter Wortwitz, oder "Bisschen" muss klein :D
Zeile 24: "zum drucken und kopieren", Drucken und Kopieren müssen Groß (nominalisierte Verben)
Zeile 41: Komma fehlt zwischen "Schlange steht" und lohnt "Schlange steht, lohn sicht."
Zeile 41: Komma fehlt zwischen "fragt" und "mit": Preissystem, je nachdem wen man fragt, mit
Zeile 41: "individuelle gerichte", Gerichte groß
Zeile 58: Komma fehlt zwischen "Anlaufstelle" und "wenn". "häufig eine Anlaufstelle, wenn man"
Zeile 78: "Print & Pay beim ZIV", komplett raus nehmen, gibts nicht mehr^^. Satz muss da etwas umformuliert werden

2022-09-20 09:58 UTC, MoosWhmr commented
> Zeile 15: Wer dies umgehen möchte: Komma hinter möchte fehlt. Zeile 17: "ein Bisschen", Entweder guter Wortwitz, oder "Bisschen" muss klein :D Zeile 24: "zum drucken und kopieren", Drucken und Kopieren müssen Groß (nominalisierte Verben) Zeile 41: Komma fehlt zwischen "Schlange steht" und lohnt "Schlange steht, lohn sicht." Zeile 41: Komma fehlt zwischen "fragt" und "mit": Preissystem, je nachdem wen man fragt, mit Zeile 41: "individuelle gerichte", Gerichte groß Zeile 58: Komma fehlt zwischen "Anlaufstelle" und "wenn". "häufig eine Anlaufstelle, wenn man" Zeile 78: "Print & Pay beim ZIV", komplett raus nehmen, gibts nicht mehr^^. Satz muss da etwas umformuliert werden

@axti98 Welche Version des Textes hast du benutzt? In der Version von Marius [1d4c018] waren bis auf das Komma in Zeile 58 schon alle Sachen korrigiert und deine Zeilenangaben stimmten auch nicht ganz überein. Ich hab jetzt nur das Komma ergänzt.

2022-09-20 15:27 UTC, willernicht commented
> > Zeile 15: Wer dies umgehen möchte: Komma hinter möchte fehlt. Zeile 17: "ein Bisschen", Entweder guter Wortwitz, oder "Bisschen" muss klein :D Zeile 24: "zum drucken und kopieren", Drucken und Kopieren müssen Groß (nominalisierte Verben) Zeile 41: Komma fehlt zwischen "Schlange steht" und lohnt "Schlange steht, lohn sicht." Zeile 41: Komma fehlt zwischen "fragt" und "mit": Preissystem, je nachdem wen man fragt, mit Zeile 41: "individuelle gerichte", Gerichte groß Zeile 58: Komma fehlt zwischen "Anlaufstelle" und "wenn". "häufig eine Anlaufstelle, wenn man" Zeile 78: "Print & Pay beim ZIV", komplett raus nehmen, gibts nicht mehr^^. Satz muss da etwas umformuliert werden
> 
> @axti98 Welche Version des Textes hast du benutzt? In der Version von Marius [[1d4c018](https://github.com/fsphys-muenster/ersti-fibel/commit/1d4c0184784a89b5bb46e1dca7a5069daf082f8a)] waren bis auf das Komma in Zeile 58 schon alle Sachen korrigiert und deine Zeilenangaben stimmten auch nicht ganz überein. Ich hab jetzt nur das Komma ergänzt.


Genau!

2022-09-21 12:16 UTC, axti98 approved these changes
Da die Frage aufkam welche Version ich genutzt habe: Gedacht habe ich die neuste, genommen eine alte xD

2022-09-22 08:30 UTC, merged